title: Johan Wieslander - Blog
email: johan.jww@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://halliom.github.io"
twitter_username: JohWies
github_username:  Halliom

permalink: /posts/:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock